spring:
  application:
    name: talkfish
  ai:
    vertex:
      ai:
        gemini:
          project-id: cobalt-logic-459719-v3
          location: us-east1
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.5



